### PR TITLE
Add troubleshooting guide

### PR DESCRIPTION
**Pull request by robin-nitrokey**
This patch adds a troubleshooting guide that provides solutions for
common issues during development.

### CODE REVIEW

**Review by szszszsz — COMMENTED** [review]
This looks like a development guide for me, thus is propose to rename it accordingly. What do you think?

**Comment by robin-nitrokey** [comment]
For me the focus is specifically on collecting common issues and their solutions.  I think a development guide should rather be a more detailed version of the quickstart guide.

**Comment by szszszsz** [comment]
Sounds good.  Just checked, and rather everything we publish under /docs is development specific anyway at this point. Eventual user guide would have to be separated properly.

**Review by szszszsz — APPROVED** [review]

**Comment by robin-nitrokey** [comment]
Yes, I think the guides in this repository should only be for development.  User guides should go on `docs.nitrokey.com`.

**Pull request merged**
