### PR TITLE
Make the nrf build process compatible with rootless containers

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
Fixes https://github.com/Nitrokey/nitrokey-3-firmware/issues/292#issuecomment-1592576681

### CODE REVIEW

**Comment by szszszsz** [comment]
I've tested it yesterday and everything works fine for me. I opt for merge as-is.
What could be added is a link to rootless Docker configuration. Ideal would be a guide, which allows to use a podman here too.

**Review by szszszsz — APPROVED** [review]
OK already

**Comment by sosthene-nitrokey** [comment]
I don't think merging it until rootfull docker users have tested it is wise.

**Comment by szszszsz** [comment]
@daringer @robin-nitrokey 
Please review that. I do not see anything blocking on this one, and noone should use root-based Docker anyway, if possible.

**Review by robin-nitrokey — APPROVED** [review]
`make clean && make` in `utils/nrf-bootloader` works for me.

**Review by daringer — APPROVED** [review]

**Comment by szszszsz** [comment]
@sosthene-nitrokey green light

**Pull request merged**
