### PR TITLE
CI: remove sha256 creation, now done during deploy

### PR DESCRIPTION
**Pull request by daringer**
* removed the sha256 call inside the `build-lpc55-nk3xn` job
* remove unused/deprecated `build-lpc55-nk3xn`
* don't put `develop` firmware images into artifacts

### CODE REVIEW

**Comment by szszszsz** [comment]
Re: hash, what about non-deploy builds?

**Comment by daringer** [comment]
jupjup, will introduce an intermediate stage which just generates hashes for the entire artifacts directory ...

**Review by robin-nitrokey — APPROVED** [review]
Can we just remove the old stuff instead of commenting it?

**Comment by szszszsz** [comment]
@daringer 
Quick question: since you are doing hashing now in a separate job, I assume the cache is flushed and the file content to be hashed is no longer in the ECC memory. This implicates, that subsequent job will read that from the disk. The produced binary in the moment of writing does not have any hash sum at all. Does the underlying file system / content storage system provide any means for the read correctness verification and against bit rotting?

**Comment by szszszsz** [comment]
> That's a hosted system, cannot tell anything about the actual underlying hardware, but at least a RAID 1 is pretty common and will likely be in place. Do you imply we should not trust (i.e., verify) write operations onto the filesystem on this machine?

I do not trust any raw binary, if it does not have immediately hash sum created. This is especially important for me for the CI release.
I do not see how the RAID 1 would meant to protect against bit rotting. It has mirrored writes and striped/round robin reads (so still can get faulty read from one of them), but no checksum on this level (RAID 3/5 offers that). 
I have found that some hard drives have integrated checksums on the hardware level, concerning whole sector, but I do not like to depend on that, and rather use "defense in depth" strategy.

**Review by szszszsz — CHANGES_REQUESTED** [review]
see comment

**Pull request closed without merging**
