### PR TITLE
wait 5 more seconds for dev to show up during provision-develop

### PR DESCRIPTION
**Pull request by runcom**
related to https://github.com/Nitrokey/nitrokey-3-firmware/issues/187#issuecomment-1484869788

just an idea, if it doesn't fit, I'll close this but so far it works with this patch

### CODE REVIEW

**Comment by runcom** [comment]
Sure thing I can change it to 5s, I’ll check if it still works but it should

**Comment by runcom** [comment]
Sure thing I can change it to 5s, I’ll check if it still works but it should

**Comment by runcom** [comment]
works perfectly with 5s too - I'll push again once github is back

**Comment by robin-nitrokey** [comment]
Interesting, thanks for the PR!  Strange that I never ran into the issue.  I’ll test and merge it after the v1.3.0 release.

**Comment by szszszsz** [comment]
@robin-nitrokey Bump - had you any chance retesting that?
I use `sleep 5` on my side.

**Review by szszszsz — APPROVED** [review]

**Pull request merged**
