### PR TITLE
Update cbor-smol

### PR DESCRIPTION
**Pull request by robin-nitrokey**

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
binary-size-nk3xn-test:

| **PR** | **value** | **change to main** |
| --- | --: | --: |
| https://github.com/Nitrokey/cbor-smol/pull/2 | 565,240 | +17,736 |
| https://github.com/Nitrokey/cbor-smol/pull/3 | 553,520 | +6,016 |
| https://github.com/Nitrokey/cbor-smol/pull/4 | 545,552 | -1,952 |

**Comment by robin-nitrokey** [comment]
@sosthene-nitrokey Should we merge this separately before #441 so that the cbor-smol update no longer affects the metrics for that PR?  Alternatively, you can just use `v0.4.0-nitrokey.3` in #441.

**Comment by sosthene-nitrokey** [comment]
I'll bump 441 to use the improved cbor-smol. Less merge conflicts.

**Comment by robin-nitrokey** [comment]
Included in https://github.com/Nitrokey/nitrokey-3-firmware/pull/441.

**Pull request closed without merging**
