### PR TITLE
nkpk: add test firmware keys and allow choosing variant in nrf-bootloader

### PR DESCRIPTION
**Pull request by daringer**
* add `utils/test-certificates/firmware-nkpk`
* extend `utils/nrf-bootloader/generate-keys.sh` to also output a public key pem
* adapt `make` toolchain in `utils/nrf-bootloader` to allow building for both variants
  * use two different config includes for `nkpk` and `nk3am` (vid:pid changes + product name)
  * now requires `TARGET=nk3am` or `nkpk`
  * adapt `utils/nrf-builder` to this
  * ci doesn't use the bootloader build, but cached builds - fine for now for both nkpk / nk3am

### CODE REVIEW

**Comment by sosthene-nitrokey** [comment]
Should the nk_sdk_config.h file not be removed?

**Comment by daringer** [comment]
but it breaks the HIL as "someone" has hardcoded paths there - fixing...

**Comment by sosthene-nitrokey** [comment]
> git calls it a rename, as the new `nk3am_sdk_config.h` is identical

Yes I was specifically surprised to see 2 new file and not a rename.

**Comment by daringer** [comment]
yup, I pushed again after making sure the file doesn't exist - now it's properly handled/shown by github too

**Comment by daringer** [comment]
hil is also working again, good to go

**Review by robin-nitrokey — APPROVED** [review]
LGTM!

nk3am provides the public key also as a PEM file, nkpk only as a C file.  remove the PEM file from nk3am or add it to nkpk?

**Comment by daringer** [comment]
good find, even updated `generate_key.sh` to do this automatically, but did not `git add` the file - fixed - updated PR

**Pull request merged**
