### PR TITLE
Release v1.7.1

### PR DESCRIPTION
**Pull request by robin-nitrokey**

### CODE REVIEW

**Review by daringer — APPROVED** [review]

**Comment by tlaurion** [comment]
@robin-nitrokey description on release would be great!

**Comment by daringer** [comment]
The release description will as always be part of the release notes - not part of the PR which bumps the version number in code.

**Comment by robin-nitrokey** [comment]
And you can also find it in the [changelog](https://github.com/Nitrokey/nitrokey-3-firmware/blob/f22e6e3fd35b30e0a817330d7878a99f0902c7b7/CHANGELOG.md#v171-2024-05-03).

**Pull request merged**
