### PR TITLE
embedded/lpc55: Gracefully handle EFS errors

### PR DESCRIPTION
**Pull request by robin-nitrokey**
Instead of panicking if the communication with the EFS fails, we set an
error flag and use RAM as a fallback.

----

This can be simulated by replacing `into_output_high` with `into_output_low` here:
https://github.com/Nitrokey/nitrokey-3-firmware/blob/c728fae23e8d31a6f514e80e0755c5193e402ca9/runners/embedded/src/soc_lpc55/init.rs#L546

@daringer Do we need something similar for NRF52?

Based on https://github.com/Nitrokey/nitrokey-3-firmware/pull/172

### CODE REVIEW

**Review by szszszsz — APPROVED** [review]
Not tested, but looks good

**Comment by szszszsz** [comment]
Can you invoke the failure case in the firmware somehow for tests? Or have you done so already?

**Comment by robin-nitrokey** [comment]
> Can you invoke the failure case in the firmware somehow for tests? Or have you done so already?

I’ve tested it by just not powering the external flash, see the PR description.

**Comment by szszszsz** [comment]
Ah, I've missed that this was a test case description. Good!

**Pull request merged**
