### PR TITLE
Fix nightly build

### PR DESCRIPTION
**Pull request by robin-nitrokey**

### CODE REVIEW

**Review by sosthene-nitrokey — CHANGES_REQUESTED** [review]
This is already part of the CI image: https://github.com/Nitrokey/nitrokey-3-firmware/blob/22fc4da6db9819ad6ba2c42c7121e5e26565a37a/Dockerfile#L5

**Comment by robin-nitrokey** [comment]
Only for the default toolchain specified in `rustup-toolchain.toml`.  This runs the build with `RUSTUP_TOOLCHAIN={stable,nightly}` but currently fails because of the missing target.

**Comment by robin-nitrokey** [comment]
[Here](https://git.nitrokey.com/nitrokey/nitrokey-3-firmware/-/jobs/108555) is an example of a failing build without `rustup target add`.

**Comment by sosthene-nitrokey** [comment]
Why did  this used to work and fails now?

Also then this should be fixed in the image definition rather than in the CI script, so that pipelines don't get longer than they have to.

**Comment by robin-nitrokey** [comment]
The idea is to run it with the latest nightly and stable Rust versions to detect incompatibilities.  If we would add them to the docker image, we would need to update the Docker image every six weeks.  As the build is only run once per day, I think we can live with the overhead of installing the toolchains on every run.

**Comment by robin-nitrokey** [comment]
> Why did this used to work and fails now?

I don’t know.  I think scheduled builds were disabled for quite some time.  And as you cannot job executions by job name, it is hard to track this down.

**Review by sosthene-nitrokey — APPROVED** [review]

**Comment by robin-nitrokey** [comment]
Ah, you can filter pipelines by trigger.  https://github.com/Nitrokey/nitrokey-3-firmware/pull/411 broke the nightly jobs because it removed the `rustup target add` call that is added again in this PR.

**Pull request merged**
